/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Amigo;
import javax.swing.JOptionPane;

public class FRMAmigo extends javax.swing.JFrame {

    private Amigo objetoamigo;
    
    public FRMAmigo() {
        initComponents();
        this.objetoamigo = new Amigo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLamigo_cadastroamigo = new javax.swing.JLabel();
        jLamigo_nome = new javax.swing.JLabel();
        jLamigo_telefone = new javax.swing.JLabel();
        jLamigo_email = new javax.swing.JLabel();
        jTFamigo_nome = new javax.swing.JTextField();
        jTFamigo_telefone = new javax.swing.JTextField();
        jTFamigo_email = new javax.swing.JTextField();
        jBamigo_voltar = new javax.swing.JButton();
        jBamigo_cadastrar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Amigos");

        jLamigo_cadastroamigo.setBackground(new java.awt.Color(255, 255, 255));
        jLamigo_cadastroamigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLamigo_cadastroamigo.setText("Cadastro de amigo");
        jLamigo_cadastroamigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLamigo_nome.setText("Nome:");

        jLamigo_telefone.setText("Telefone:");

        jLamigo_email.setText("E-mail:");

        jTFamigo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFamigo_nomeActionPerformed(evt);
            }
        });

        jBamigo_voltar.setText("Voltar");
        jBamigo_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBamigo_voltarActionPerformed(evt);
            }
        });

        jBamigo_cadastrar.setText("Cadastrar");
        jBamigo_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBamigo_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLamigo_telefone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLamigo_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLamigo_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFamigo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFamigo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFamigo_email, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBamigo_voltar)
                                .addGap(157, 157, 157)
                                .addComponent(jBamigo_cadastrar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLamigo_cadastroamigo)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLamigo_cadastroamigo)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamigo_nome)
                    .addComponent(jTFamigo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamigo_telefone)
                    .addComponent(jTFamigo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLamigo_email)
                    .addComponent(jTFamigo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBamigo_voltar)
                    .addComponent(jBamigo_cadastrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFamigo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFamigo_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFamigo_nomeActionPerformed

    private void jBamigo_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBamigo_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBamigo_voltarActionPerformed

    private void jBamigo_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBamigo_cadastrarActionPerformed
        try {
            String nome = this.jTFamigo_nome.getText();
            String telefone = this.jTFamigo_telefone.getText();
            String email = this.jTFamigo_email.getText();
            if (nome.length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            }
            if (telefone.isEmpty() || telefone.length() < 2) {
                throw new Mensagens("Telefone deve conter ao menos 2 caracteres.");
            }
            if (email.length() < 2) {
                throw new Mensagens("E-mail deve conter ao menos 2 caracteres.");
            }
            if (this.objetoamigo.insertAmigoBD(nome, telefone, email)) {
                JOptionPane.showMessageDialog(null, "Amigo Cadastrado com Sucesso!");
                this.jTFamigo_nome.setText("");
                this.jTFamigo_telefone.setText("");
                this.jTFamigo_email.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao cadastrar amigo.");
            }
            System.out.println(this.objetoamigo.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jBamigo_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBamigo_cadastrar;
    private javax.swing.JButton jBamigo_voltar;
    private javax.swing.JLabel jLamigo_cadastroamigo;
    private javax.swing.JLabel jLamigo_email;
    private javax.swing.JLabel jLamigo_nome;
    private javax.swing.JLabel jLamigo_telefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFamigo_email;
    private javax.swing.JTextField jTFamigo_nome;
    private javax.swing.JTextField jTFamigo_telefone;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
