/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Ferramenta;
import javax.swing.JOptionPane;
/**
 *
 * @author 10723114087
 */
public class FRMFerramenta extends javax.swing.JFrame {
    
    private Ferramenta objetoferramenta;
    
    public FRMFerramenta() {
        initComponents();
        this.objetoferramenta = new Ferramenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLferramenta_cadastroferramenta = new javax.swing.JLabel();
        jLferramenta_nome = new javax.swing.JLabel();
        jLferramenta_marca = new javax.swing.JLabel();
        jLferramenta_custo = new javax.swing.JLabel();
        jTFferramenta_nome = new javax.swing.JTextField();
        jTFferramenta_marca = new javax.swing.JTextField();
        jTFferramenta_custo = new javax.swing.JTextField();
        jBferramenta_voltar = new javax.swing.JButton();
        jBferramenta_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Ferramentas");

        jLferramenta_cadastroferramenta.setBackground(new java.awt.Color(255, 255, 255));
        jLferramenta_cadastroferramenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLferramenta_cadastroferramenta.setText("Cadastro ferramenta");
        jLferramenta_cadastroferramenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLferramenta_nome.setText("Nome:");

        jLferramenta_marca.setText("Marca:");

        jLferramenta_custo.setText("Custo R$:");

        jTFferramenta_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFferramenta_nomeActionPerformed(evt);
            }
        });

        jBferramenta_voltar.setText("Voltar");
        jBferramenta_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBferramenta_voltarActionPerformed(evt);
            }
        });

        jBferramenta_cadastrar.setText("Cadastrar");
        jBferramenta_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBferramenta_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLferramenta_marca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLferramenta_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLferramenta_custo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFferramenta_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFferramenta_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFferramenta_custo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBferramenta_voltar)
                                .addGap(165, 165, 165)
                                .addComponent(jBferramenta_cadastrar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLferramenta_cadastroferramenta)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLferramenta_cadastroferramenta)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLferramenta_nome)
                    .addComponent(jTFferramenta_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLferramenta_marca)
                    .addComponent(jTFferramenta_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLferramenta_custo)
                    .addComponent(jTFferramenta_custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBferramenta_voltar)
                    .addComponent(jBferramenta_cadastrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFferramenta_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFferramenta_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFferramenta_nomeActionPerformed

    private void jBferramenta_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBferramenta_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBferramenta_voltarActionPerformed

    private void jBferramenta_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBferramenta_cadastrarActionPerformed
        try {
            String nome = this.jTFferramenta_nome.getText();
            String marca = this.jTFferramenta_marca.getText();
            String custoStr = this.jTFferramenta_custo.getText();
            
            if (nome.length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            }
            
            if (marca.isEmpty() || marca.length() < 2) {
                throw new Mensagens("Marca deve conter ao menos 2 caracteres.");
            }
            
            double custo;
            try {
                custo = Double.parseDouble(custoStr);
            } catch (NumberFormatException e) {
                throw new Mensagens("Custo deve ser um número válido.");
            }
            
            if (this.objetoferramenta.insertFerramentaBD(nome, marca, custo)) {
                JOptionPane.showMessageDialog(null, "Ferramenta Cadastrada com Sucesso!");
                this.jTFferramenta_nome.setText("");
                this.jTFferramenta_marca.setText("");
                this.jTFferramenta_custo.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao cadastrar ferramenta.");
            }
            System.out.println(this.objetoferramenta.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jBferramenta_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBferramenta_cadastrar;
    private javax.swing.JButton jBferramenta_voltar;
    private javax.swing.JLabel jLferramenta_cadastroferramenta;
    private javax.swing.JLabel jLferramenta_custo;
    private javax.swing.JLabel jLferramenta_marca;
    private javax.swing.JLabel jLferramenta_nome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFferramenta_custo;
    private javax.swing.JTextField jTFferramenta_marca;
    private javax.swing.JTextField jTFferramenta_nome;
    // End of variables declaration//GEN-END:variables
}
