package View;

import Model.Amigo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FRMRelatorioAmigos extends javax.swing.JFrame {
    
    private Amigo objetoamigo;
    
    public FRMRelatorioAmigos() {
        initComponents();
        this.objetoamigo = new Amigo();
        this.carregaTabela();
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTativos = new javax.swing.JTable();
        jBrelatorioAtivos_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório de amigos");

        jTativos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Telefone", "E-mail"
            }
        ));
        jTativos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTativosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTativos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTativosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTativos);

        jBrelatorioAtivos_voltar.setText("Voltar");
        jBrelatorioAtivos_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrelatorioAtivos_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jBrelatorioAtivos_voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jBrelatorioAtivos_voltar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBrelatorioAtivos_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrelatorioAtivos_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBrelatorioAtivos_voltarActionPerformed

    private void jTativosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTativosAncestorAdded

    }//GEN-LAST:event_jTativosAncestorAdded

    private void jTativosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTativosMouseClicked
        if (this.jTativos.getSelectedRow() != -1) {
            String nome = this.jTativos.getValueAt(this.jTativos.getSelectedRow(), 1).toString();
            String telefone = this.jTativos.getValueAt(this.jTativos.getSelectedRow(), 2).toString();
            String email = this.jTativos.getValueAt(this.jTativos.getSelectedRow(), 3).toString();
          
        } 
    }//GEN-LAST:event_jTativosMouseClicked

    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTativos.getModel();
        modelo.setNumRows(0);
        ArrayList<Amigo> minhalista = objetoamigo.getMinhaLista();
        for (Amigo a : minhalista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getTelefone(),
                a.getEmail()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMRelatorioAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FRMRelatorioAmigos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBrelatorioAtivos_voltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTativos;
    // End of variables declaration//GEN-END:variables
}
