/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import Model.Emprestimo;
import javax.swing.JOptionPane;
/**
 *
 * @author 1072324171
 */
public class FRMRegistroEmprestimos extends javax.swing.JFrame {

    private Emprestimo objetoemprestimo;
    
    public FRMRegistroEmprestimos() {
        initComponents();
        this.objetoemprestimo = new Emprestimo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFregistroEmprestimo_nome = new javax.swing.JTextField();
        jTFregistroEmprestimo_telefone = new javax.swing.JTextField();
        jBRegistroemprestimo_voltar = new javax.swing.JButton();
        jBregistroEmprestimo_cadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFregistroEmprestimo_dataretirada = new javax.swing.JTextField();
        jTFregistroEmprestimo_prevEntrega = new javax.swing.JTextField();
        jTFregistroEmprestimo_Ferramenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Insira os dados para empréstimo");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Ferramenta:");

        jTFregistroEmprestimo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFregistroEmprestimo_nomeActionPerformed(evt);
            }
        });

        jBRegistroemprestimo_voltar.setText("Voltar");
        jBRegistroemprestimo_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistroemprestimo_voltarActionPerformed(evt);
            }
        });

        jBregistroEmprestimo_cadastrar.setText("Cadastrar");
        jBregistroEmprestimo_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistroEmprestimo_cadastrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Data:");

        jLabel6.setText("Prev. Entrega:");

        jTFregistroEmprestimo_dataretirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFregistroEmprestimo_dataretiradaActionPerformed(evt);
            }
        });

        jTFregistroEmprestimo_prevEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFregistroEmprestimo_prevEntregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFregistroEmprestimo_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jTFregistroEmprestimo_telefone)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jBRegistroemprestimo_voltar))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBregistroEmprestimo_cadastrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFregistroEmprestimo_prevEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTFregistroEmprestimo_dataretirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTFregistroEmprestimo_Ferramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFregistroEmprestimo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFregistroEmprestimo_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFregistroEmprestimo_Ferramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFregistroEmprestimo_dataretirada, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFregistroEmprestimo_prevEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegistroemprestimo_voltar)
                    .addComponent(jBregistroEmprestimo_cadastrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFregistroEmprestimo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFregistroEmprestimo_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFregistroEmprestimo_nomeActionPerformed

    private void jTFregistroEmprestimo_dataretiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFregistroEmprestimo_dataretiradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFregistroEmprestimo_dataretiradaActionPerformed

    private void jTFregistroEmprestimo_prevEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFregistroEmprestimo_prevEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFregistroEmprestimo_prevEntregaActionPerformed

    private void jBRegistroemprestimo_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistroemprestimo_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBRegistroemprestimo_voltarActionPerformed

    private void jBregistroEmprestimo_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistroEmprestimo_cadastrarActionPerformed
        try {
            String nome = this.jTFregistroEmprestimo_nome.getText();
            String telefone = this.jTFregistroEmprestimo_telefone.getText();
            String ferramenta = this.jTFregistroEmprestimo_Ferramenta.getText();
            String dataRetiradaStr = this.jTFregistroEmprestimo_dataretirada.getText();
            String dataPrevistaDevolucaoStr = this.jTFregistroEmprestimo_prevEntrega.getText();
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date dataRetirada = dateFormat.parse(dataRetiradaStr);
            Date dataPrevistaDevolucao = dateFormat.parse(dataPrevistaDevolucaoStr);

            
            if (nome.length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            }
        
            if (telefone.isEmpty() || telefone.length() < 2) {
                throw new Mensagens("Telefone deve conter ao menos 2 caracteres.");
            }
        
            if (ferramenta.length() < 2) {
                throw new Mensagens("Ferramenta deve conter ao menos 2 caracteres.");
            }
        
            Date dataRetirada;
            Date dataPrevistaDevolucao;
            try {
                dataRetirada = dateFormat.parse(dataRetiradaStr);
                dataPrevistaDevolucao = dateFormat.parse(dataPrevistaDevolucaoStr);
            } catch (ParseException e) {
                throw new Mensagens("Datas devem estar no formato dd/MM/yyyy.");
            }
            
            if (this.objetoemprestimo.insertEmprestimoBD(nome, telefone, ferramenta, dataRetirada, dataPrevistaDevolucao)) {
                JOptionPane.showMessageDialog(null, "Empréstimo Cadastrado com Sucesso!");
                this.jTFregistroEmprestimo_nome.setText("");
                this.jTFregistroEmprestimo_telefone.setText("");
                this.jTFregistroEmprestimo_Ferramenta.setText("");
                this.jTFregistroEmprestimo_dataretirada.setText("");
                this.jTFregistroEmprestimo_prevEntrega.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Falha ao cadastrar empréstimo.");
            }
            System.out.println(this.objetoemprestimo.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (ParseException erro2) {
            JOptionPane.showMessageDialog(null, "Erro ao converter data: " + erro2.getMessage());
        }
    }//GEN-LAST:event_jBregistroEmprestimo_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMRegistroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMRegistroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMRegistroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMRegistroEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMRegistroEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRegistroemprestimo_voltar;
    private javax.swing.JButton jBregistroEmprestimo_cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFregistroEmprestimo_Ferramenta;
    private javax.swing.JTextField jTFregistroEmprestimo_dataretirada;
    private javax.swing.JTextField jTFregistroEmprestimo_nome;
    private javax.swing.JTextField jTFregistroEmprestimo_prevEntrega;
    private javax.swing.JTextField jTFregistroEmprestimo_telefone;
    // End of variables declaration//GEN-END:variables
}
