/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Ferramenta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class FRMRelatorioFerramentas extends javax.swing.JFrame {
    
    public FRMRelatorioFerramentas() {
        initComponents();
        carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jBRelatorioFerramentas_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFrelatorio_custoTotal = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório de ferramentas");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Ferramenta", "Marca", "Custo"
            }
        ));
        jTable2.setToolTipText("");
        jScrollPane2.setViewportView(jTable2);

        jBRelatorioFerramentas_voltar.setText("Voltar");
        jBRelatorioFerramentas_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRelatorioFerramentas_voltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Custo total:");

        jTFrelatorio_custoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFrelatorio_custoTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFrelatorio_custoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRelatorioFerramentas_voltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFrelatorio_custoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jBRelatorioFerramentas_voltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRelatorioFerramentas_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRelatorioFerramentas_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBRelatorioFerramentas_voltarActionPerformed

    private void jTFrelatorio_custoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFrelatorio_custoTotalActionPerformed
        calcularCustoTotal();
    }//GEN-LAST:event_jTFrelatorio_custoTotalActionPerformed
    
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        modelo.setNumRows(0);
        Ferramenta ferramenta = new Ferramenta();
        ArrayList<Ferramenta> ferramentas = ferramenta.getMinhaLista();
        for (Ferramenta f : ferramentas) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getMarca(),
                f.getCusto()
            });
        }
        calcularCustoTotal();
    }
    
    private void calcularCustoTotal() {
        double custoTotal = 0.0;
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        int rowCount = modelo.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            double custoFerramenta = Double.parseDouble(modelo.getValueAt(i, 3).toString());
            custoTotal += custoFerramenta;
        }
        jTFrelatorio_custoTotal.setText(String.valueOf(custoTotal));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new FRMRelatorioFerramentas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRelatorioFerramentas_voltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFrelatorio_custoTotal;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
